customhost = "database-1.cvy7wbz5p7ok.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "teechizhe-bucket"
customregion = "us-east-1"